spring:
  application:
    name: service-feign
  mvc:
    static-path-pattern: /**
  data:
    elasticsearch:
      ####集群名称
      cluster-name: wfy
      ####地址
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enable: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
server:
  port: 8085
feign:
  hystrix:
    enabled: false
