server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
spring:
  application:
    name: travel-service
  datasource:
    url: jdbc:mysql://localhost:3306/wfy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml

